### ISSUE TITLE
File Creation Issue

### ISSUE THREAD

**Issue by ttadesse627** [natipro22/CodeCLI#1]
For a specified file with its path like "dotnet code g c MySubFolder/MyClasses/ClassA", it should:

1. Create a class called "ClassA" in the folder "MySubFolder/MyClasses/" in the current directory.
2. If the current directory doesn't contain folder "MySubFolder/MyClasses/", it should create it and create a file "ClassA.cs" in it.
3. The Class name should be similar to the file name created.
4. The namespace should be similar to the folder path. e.g. "using <<parentpath>>.MySubFolder.MyClasses;"

**Comment by natipro22** [comment]
thanks done.

**Comment by natipro22** [comment]
Fixed
